# Binary Sensor yaml

- platform: template
  sensors:
    home_occupancy:
      friendly_name: Home Occupancy
      icon_template: >-
        {% if is_state('binary_sensor.home_occupancy', 'on') %}
          mdi:home-account
        {% else %}
          mdi:home-outline
        {% endif %}
      value_template: "{{ is_state('person.mark','home') or is_state('person.holly','home') or is_state('switch.visitors','on') }}"

- platform: ping
  host: 192.168.68.103
  name: "breezewayRA"
  count: 4
  scan_interval: 300

- platform: ping
  host: 192.168.68.111
  name: "LivingroomRA"
  count: 4
  scan_interval: 300

- platform: ping
  host: 192.168.68.108
  name: "Mark Ping"
  count: 4
  scan_interval: 600