# Binary Sensor yaml

- platform: template
  sensors:
    home_occupancy:
      friendly_name: Home Occupancy
      icon_template: >-
        {% if is_state('binary_sensor.home_occupancy', 'on') %}
          mdi:home-account
        {% else %}
          mdi:home-outline
        {% endif %}
      value_template: "{{ is_state('person.mark','home') or is_state('person.holly','home') or is_state('switch.visitors','on') }}"
