# Loads default set of integrations. Do not remove.
default_config:

# my:

http:
# SSL Certificate locations
  ssl_certificate: !secret fullchain
  ssl_key: !secret privkey
# server host to listen only ipv4 kill ipv6
#  server_host: 192.168.68.10
# IP BAN
#  ip_ban_enabled: true
#  login_attempts_threshold: 3

homeassistant:
#  external_url: !secret externalurl
#  internal_url: !secret internalurl

cloud:

# mobile_app:

wake_on_lan:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
# see if theis takes care of lovelace uncaught 0:0 in log files
#  extra_module_url:
#    - /config/www/community/lovelace-card-mod/card-mod.js

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include groups.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
input_text: !include input_texts.yaml
input_button: !include input_buttons.yaml
notify: !include notifys.yaml
template: !include templates.yaml
switch: !include switchs.yaml

# withings entry true every 120 minutes - false every 10 minutes
withings:
    use_webhook: true

# Following add devices to sidebar for quick access
#panel_custom:  
#  - name: Devices
#    sidebar_title: Devices
#    sidebar_icon: mdi:devices
#    js_url: /api/hassio/app/entrypoint.js
#    url_path: config/devices/dashboard
#    embed_iframe: true
#    require_admin: true
#    config:
#      ingress: core_configurator

# For mounting SMB Network media
# Note - if the mount doesn't work, substitute vers=3.0 with  vers=1.0 or vers=2.1
shell_command:
  pushupdates_to_github: /bin/bash pushupdates.sh

logger:
  default: warning
  logs:
    custom_components.hass_agent: debug
    