##################
## sensors.yaml ##
##################

# date and time sensors
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'

- platform: rest
  name: Dad Joke
  unique_id: dad_joke
  resource: https://api.api-ninjas.com/v1/dadjokes?limit=1
  method: GET
  scan_interval: 7200
  headers:
    X-Api-Key: !secret ninjas_api
  value_template: "{{ value_json[0].joke }}"

- platform: rest
  name: Riddle
  unique_id: e70479b3-a94f-4778-9727-9474414bec50
  resource: https://api.api-ninjas.com/v1/riddles
  method: GET
  scan_interval: 7200
  headers:
    X-Api-Key: !secret ninjas_api
  value_template: "{{ value_json[0].title }}"
  json_attributes_path: "$.[0]"
  json_attributes:
    - "question"
    - "answer"  

# One entry for each beacon you want to track
- platform: mqtt_room
  device_id: "50f14a7a58f2"
  name: 'Fob One esp'
  state_topic: 'espresense/devices/50f14a7a58f2'
  timeout: 10
  away_timeout: 120

- platform: mqtt_room
  device_id: "iBeacon:f2d3fa15-34f5-000f-c225-7b7c1140ffc0-0-0"
  name: 'Mark Watch S3 esp'
  state_topic: 'espresense/devices/iBeacon:f2d3fa15-34f5-000f-c225-7b7c1140ffc0-0-0'
  timeout: 10
  away_timeout: 10

- platform: mqtt_room
  device_id: "apple:1005:9-12"
  name: 'iPhone esp'
  state_topic: 'espresense/devices/apple:1005:9-12'
  timeout: 10
  away_timeout: 10

- platform: mqtt_room
  device_id: "iBeacon:d23d8613-c3fd-44af-a5df-59e16d1c777f-100-1"
  name: 'Mark Phone esp'
  state_topic: 'espresense/devices/iBeacon:d23d8613-c3fd-44af-a5df-59e16d1c777f-100-1'
  timeout: 10
  away_timeout: 10

- platform: mqtt_room
  device_id: "iBeacon:60718bec-7548-45ea-ad35-ef51ecdc3ee9-100-1"
  name: 'Holly Phone esp'
  state_topic: 'espresense/devices/iBeacon:60718bec-7548-45ea-ad35-ef51ecdc3ee9-100-1'
  timeout: 10
  away_timeout: 10

- platform: mqtt_room
  device_id: "iBeacon:d775884c-ed66-40fb-af86-bd19e8b048e6-100-1"
  name: 'Samsung A11 esp'
  state_topic: 'espresense/devices/iBeacon:d775884c-ed66-40fb-af86-bd19e8b048e6-100-1'
  timeout: 10
  away_timeout: 10

- platform: mqtt_room
  device_id: "iBeacon:426c7565-4368-6172-6d42-6561636f6e73-3838-4949"
  name: 'Holly Car esp'
  state_topic: 'espresense/devices/iBeacon:426c7565-4368-6172-6d42-6561636f6e73-3838-4949'
  timeout: 10
  away_timeout: 10

- platform: mqtt_room
  device_id: "iBeacon:426c7565-4368-6172-6d42-6561636f6e73-3839-4950"
  name: 'Mark Car esp'
  state_topic: 'espresense/devices/iBeacon:426c7565-4368-6172-6d42-6561636f6e73-3839-4950'
  timeout: 10
  away_timeout: 10


# sensor check for office lights turning on mid automation/for override
#- platform: history_stats
#  name: Office Count
#  entity_id: light.upstairs_office
#  state: "on"
#  type: count
#  end: "{{ now() }}"
#  duration:
#    minutes: 1

