# minutes until next alarm
- platform: template
  sensors:
    holly_next_alarm:
      friendly_name: "Minutes until Hollys Next Alarm"
      unit_of_measurement: 'm'
      entity_id: sensor.time
      value_template: "{{((states('sensor.sm_g960u_next_alarm')|as_timestamp|int - now()|as_timestamp|int)/60)|int}}"
      availability_template: "{{ not is_state('sensor.sm_g960u_next_alarm','unavailable') }}"
      attribute_templates:
        time: "{{ state_attr('sensor.sm_g960u_next_alarm','Local Time') }}"
        
    mark_next_alarm:
      friendly_name: "Minutes until Marks Next Alarm"
      unit_of_measurement: 'm'
      entity_id: sensor.time
      value_template: "{{((states('sensor.sm_n960u_next_alarm')|as_timestamp|int - now()|as_timestamp|int)/60)|int}}"
      availability_template: "{{ not is_state('sensor.sm_n960u_next_alarm','unavailable') }}"
      attribute_templates:
        time: "{{ state_attr('sensor.sm_n960u_next_alarm','Local Time') }}"

# dae and time sensors
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'
