##################
## sensors.yaml ##
##################

# date and time sensors
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'

# sensor check for office lights turning on mid automation/for override
#- platform: history_stats
#  name: Office Count
#  entity_id: light.upstairs_office
#  state: "on"
#  type: count
#  end: "{{ now() }}"
#  duration:
#    minutes: 1

