##################
## switchs.yaml ##
##################

- platform: wake_on_lan
  name: "Dell Tower On"
  mac: !secret dellmac
  broadcast_port: 7
        
- platform: wake_on_lan
  name: "ASUS Tower On"
  mac: !secret asusmac
  broadcast_port: 7
