esphome:
  name: green
  friendly_name: Green

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "QWR5umUD+3iBlij/5kwhWDv/drEv2LGEaAbscagvnVs="

ota:
  password: "02a6648d1c15fdac83cbdab109332a9c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Green Fallback Hotspot"
    password: "zsyDkV6jZ2G7"

web_server:
  port: 80

# captive_portal:

binary_sensor:
  - platform: gpio
    pin: GPIO14
    id: sensor
    name: "Sensor"
    device_class: garage_door

switch:
  - platform: gpio
    pin: GPIO12
    id: relay
    
  - platform: template
    icon: "mdi:dog"
    name: "Door"
    turn_on_action:
    - switch.turn_on: relay
    - delay: 1s
    - switch.turn_off: relay

cover:
  - platform: template
    name: Opener
    device_class: garage
    lambda: !lambda |-
      if (id(sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_on: relay
      - delay: 1s
      - switch.turn_off: relay
    close_action:
      - switch.turn_on: relay
      - delay: 1s
      - switch.turn_off: relay
    stop_action:
      - switch.turn_on: relay
      - delay: 1s
      - switch.turn_off: relay